steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build docker image
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      docker build ./go-app -t gcr.io/meeting-nanny/random-name-picker:latest

- name: 'gcr.io/cloud-builders/docker'
  id: push docker image to container registry
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      docker push gcr.io/meeting-nanny/random-name-picker:latest

- name: 'gcr.io/cloud-builders/gcloud'
  id: get cluster details
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials google-cloud-next --zone=us-central1-a --project meeting-nanny

- name: 'gcr.io/cloud-builders/kubectl'
  id: apply deployment to kubernetes
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      kubectl set image deployment/random-name-picker random-name-picker=gcr.io/meeting-nanny/random-name-picker:latest
